#!/bin/bash

# This script must be sudo authorized for _www to run as podclient

#include localdefs
source $(dirname $0)/../etc/localdefs

ACTION=$1
CUTLIST_FILE=$2
DATE=`date +%s`
if [ "$ACTION" == "resume" ] 
then 
DATE=$[ $DATE + 5 ]
fi

echo $ACTION:$DATE:`date +"%Y_%m_%d_%Hh%M"` >> $CUTLIST_FILE

