#!/bin/bash -x

# This script must be sudo authorized for _www to run as podclient

#include localdefs
source $(dirname $0)/../etc/localdefs

#asset not used yet
ASSET=$1

unlink $EZCASTDIR/var/_monitoring_pid

#stop recording 
PID=`cat $FFMPEG_PID`
# ends FFMPEG
kill -9 $PID
while ps -p $PID > /dev/null; do sleep 1; done
unlink $FFMPEG_PID

# same process for pid2 if set
if [ -e $FFMPEG_PID2 ]
then
    PID2=`cat $FFMPEG_PID2`
    kill -9 $PID2
    while ps -p $PID2 > /dev/null; do sleep 1; done
    unlink $FFMPEG_PID2
fi