#!/bin/bash -x

#include localdefs
source $(dirname $0)/../etc/localdefs

COURSE=$1
SDAT=$2
PROCESSING_TOOL=$3
STORDIR=$RECORDDIR/local_processing/ffmpeg_${SDAT}_$COURSE

#stop monitoring
unlink $EZCASTDIR/var/_monitoring_pid

#stop recording 
PID=`cat $FFMPEG_PID`
kill -2 $PID
while ps -p $PID > /dev/null; do sleep 1; done

# same process for pid2 if set
if [ -e $FFMPEG_PID2 ]
then
    PID2=`cat $FFMPEG_PID2`
    kill -2 $PID2
    while ps -p $PID2 > /dev/null; do sleep 1; done
    unlink $FFMPEG_PID2
fi

METADATAPATH=$EZCASTDIR/var/${SDAT}_$COURSE/_metadata.xml


echo "EZrecorder : saving camera movie to $STORDIR<br>"
mkdir $STORDIR
mv $MOVIESDIR/${COMMON_MOVIE_NAME}* $STORDIR 
mv $EZCASTDIR/var/ffmpeg.log $STORDIR
#copy metadata
cp $METADATAPATH  $STORDIR/metadata.xml

/usr/bin/nice -n 10 $EZCASTDIR/bash/ffmpeg_process_recording $COURSE $SDAT $PROCESSING_TOOL >> $STORDIR/processing.log 2>&1
