#!/bin/bash -x

#include localdefs
source $(dirname $0)/../etc/localdefs

unlink $EZCASTDIR/var/_monitoring_pid

#stop recording 
PID=`cat $FFMPEG_PID`
# ends FFMPEG
kill -2 $PID
#todo: kill timeout
while ps -p $PID > /dev/null; do sleep 1; done
unlink $FFMPEG_PID

# same process for pid2 if set
if [ -e $FFMPEG_PID2 ]
then
    PID2=`cat $FFMPEG_PID2`
    kill -2 $PID2
    while ps -p $PID2 > /dev/null; do sleep 1; done
    unlink $FFMPEG_PID2
fi