#!/bin/bash -x

# This script must be sudo authorized for _www to run as podclient

#include localdefs
source $(dirname $0)/../etc/localdefs

ASSET=$1

# removes all temp files used for the recording
rm -rf $STORDIR/*/low