#!/bin/bash -x

#include localdefs
source $(dirname $0)/localdefs

ASSET=$1
PROCESSING_TOOL=$2

HANDLE_SOURCE_DIR=$EZCASTDIR/handle_source/$PROCESSING_TOOL
STORDIR=$RECORDDIR/local_processing/${ASSET}

echo "command: qtb_process_recording $ASSET"
#merge movies 
echo "local merge_qtb_movies.php<br>";
$PHP_PATH $HANDLE_SOURCE_DIR/merge_qtb_movies.php $STORDIR ${COMMON_MOVIE_NAME} cam.mov
