#!/bin/bash -x

#include localdefs
source $(dirname $0)/localdefs

#first clean up eventual movie remains
SDAT=`date +"%Y_%m_%d_%Hh%M"`
echo $SDAT > $STARTRECTIMEPATH

ASSET=$1

mkdir  $RECORDDIR/trash/$SDAT 
osascript $EZCASTDIR/applescript/qtbstopmovierec.scpt&
wait
mv $RECORDDIR/${COMMON_MOVIE_NAME}*.mov  $RECORDDIR/trash/$SDAT/
unlink $EZCASTDIR/var/_monitoring_pid
if [ "$ASSET" != "" ]
then
rm -rf $EZCASTDIR/var/${ASSET}
fi
