#!/bin/bash -x

#include localdefs
source $(dirname $0)/localdefs

CALLS=$1

MAXCALLS=3 	# sends a mail after 3 fails

#first clean up eventual movie remaining
SDAT=`date +"%Y_%m_%d_%Hh%M"`
mkdir  $RECORDDIR/trash/$SDAT 
mv $RECORDDIR/${COMMON_MOVIE_NAME}*.mov  $RECORDDIR/trash/$SDAT/

osascript $EZCASTDIR/applescript/qtbstartmovierec.scpt&
wait

SDAT=`date +"%s"` 	#start date
WAITING_DELAY=4 	#if the file doesn't exist after 4s, we consider QTB has planted
EXISTS_CAM=0 		# 1 if ${COMMON_MOVIE_NAME}.mov exists on podcv

# loop while delay hasn't expired and cam file doesn't exist
while [ $(( `date +"%s"`- $SDAT )) -le $WAITING_DELAY -a \( $EXISTS_CAM -eq 0 \) ]
do 
	# if cam didn't exist yet, checks if it exists now
	[ $EXISTS_CAM -eq 0 ] && test -e $RECORDDIR/${COMMON_MOVIE_NAME}.mov && EXISTS_CAM=1;
	# if slide or cam doesn't exist yet, wait 
	if [ $EXISTS_CAM -eq 0 ]
	then
		sleep 0.5
	fi
done

#stop recording 
osascript $EZCASTDIR/applescript/qtbpausemovierec.scpt&
wait

# delete ${COMMON_MOVIE_NAME}.mov files 
rm $RECORDDIR/${COMMON_MOVIE_NAME}*.mov  
wait

# add entry in log file 
[ $CALLS -eq 1 ] && echo "********************************************" >> $EZCASTDIR/var/_dualqtbcheck_log
[ $CALLS -gt 1 ] && echo "--------------------------------------------" >> $EZCASTDIR/var/_dualqtbcheck_log
echo `date +"%d/%m/%y - %Hh%Mm%Ss"` : Attempt $CALLS >> $EZCASTDIR/var/_dualqtbcheck_log
echo "--------------------------------------------" >> $EZCASTDIR/var/_dualqtbcheck_log

if [ $EXISTS_CAM -eq 1 ]
then 
    echo "CAM (podcv)   : Success" >> $EZCASTDIR/var/_dualqtbcheck_log
    echo -n "open" > $EZCASTDIR/var/status
else 
    echo "CAM (podcv)   : Failure" >> $EZCASTDIR/var/_dualqtbcheck_log 
    echo -n "launch_failure" > $EZCASTDIR/var/status    
fi

# trigger retries
if [ $EXISTS_CAM -eq 0 ]
then 
	if [ $CALLS -lt $MAXCALLS ]
	then
                # Retry
		# Quit QTB
		osascript $EZCASTDIR/applescript/qtbquit.scpt&
		wait
		# Kill QTB if it hasn't been quit
		QTB_CAM_PID=`ps ax | grep -i "QuickTime Broadcaster" | grep -v grep | cut -c 1-6`
		# Test if QTB_CAM_PID is set
		if [ $QTB_CAM_PID -gt 0 ]; then kill -9 $QTB_CAM_PID; fi;

		$EZCASTDIR/bash/qtbnew $(( $CALLS + 1 ))
	else
                #abandon
		echo "FAILURE QTB"
		echo "QTB Launch Failure in $CLASSROOM" | mail -s "QTB Failure $CLASSROOM" $MAIL_TO
	fi
fi