#!/bin/bash -x

#include localdefs
source $(dirname $0)/localdefs

if [ $# -eq 0 ]
then 
    CALLS=1
else 
    CALLS=$1
fi

#copy saved QTB prefs to the working prefs. This is done to avoid bad/destroyed prefs
cp "$EZCASTDIR/etc/com.apple.QuickTime Broadcaster.plist" "$USERQTBPREFS"
#open new movie recording in quicktime on both machines
osascript $EZCASTDIR/applescript/qtbnewmovie.scpt&
wait
#sleep 4
$EZCASTDIR/bash/resetpositionsqtb
#osascript $EZCASTDIR/applescript/positionqtb.scpt
$EZCASTDIR/bash/qtbcheck $CALLS 
exit $?