#!/bin/bash -x

#include localdefs
source $(dirname $0)/localdefs

#first clean up eventual movie remains
SDAT=`date +"%Y_%m_%d_%Hh%M"`
echo $SDAT > $STARTRECTIMEPATH

mkdir  $RECORDDIR/trash/$SDAT 
mv $RECORDDIR/${COMMON_MOVIE_NAME}*.mov  $RECORDDIR/trash/$SDAT/
osascript $EZCASTDIR/applescript/qtbstartmovierec.scpt&
wait
#start monitoring 
echo "$PHP_PATH $EZCASTDIR/cli_monitoring.php" | at now
