#!/bin/bash -x

#include localdefs
source $(dirname $0)/localdefs

ASSET=$1
PROCESSING_TOOL=$2

STORDIR=$RECORDDIR/local_processing/$ASSET

#stop recording 
osascript $EZCASTDIR/applescript/qtbstopmovierec.scpt&

#stop monitoring
unlink $EZCASTDIR/var/_monitoring_pid

echo "podcv:saving camera movie to $STORDIR<br>"
mkdir $STORDIR
mv $RECORDDIR/${COMMON_MOVIE_NAME}*.mov $STORDIR 

/usr/bin/nice -n 10 $EZCASTDIR/bash/qtb_process_recording $ASSET $PROCESSING_TOOL >> $STORDIR/processing.log 2>&1
