#!/bin/bash 

#include localdefs
source $(dirname $0)/localdefs

#filename and path of the result (cropped) image
LOCALSCREENSHOTPATH=$1

#take the snapshot and send it to the fifo
screencapture -x -t tiff /tmp/screencapture.tiff
#warning CICrop rectangle=x_origing,y_origin,width,height 0,0 point is at bottom left!
$EZCASTDIR/bin/CoreImageTool load myimage /tmp/screencapture.tiff filter myimage CICrop rectangle=23,358,235,157 store myimage $LOCALSCREENSHOTPATH public.jpeg&
