#!/bin/bash -x

# EZCAST EZrecorder
#
# Copyright (C) 2014 Université libre de Bruxelles
#
# Written by Michel Jansens <mjansens@ulb.ac.be>
# 	     Arnaud Wijns <awijns@ulb.ac.be>
# UI Design by Julien Di Pietrantonio
#
# This software is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#include localdefs
source $(dirname $0)/localdefs

unlink $EZCASTDIR/var/_monitoring_pid

#stop recording 
PID=`cat $FFMPEG_PID`
# ends FFMPEG
kill -2 $PID
while ps -p $PID > /dev/null; do sleep 1; done

#Finally clean up eventual movie remains
SDAT=`date +"%Y_%m_%d_%Hh%M"`
ASSET=$1

unlink $FFMPEG_PID

mkdir  $RECORDDIR/trash/$SDAT 
wait
mv $MOVIESDIR/${COMMON_MOVIE_NAME}*  $RECORDDIR/trash/$SDAT/
mv $RECORDDIR/ffmpeg.log  $RECORDDIR/trash/$SDAT/
if [ "$ASSET" != "" ]
then
mv $EZCASTDIR/var/$ASSET/_cut_list $RECORDDIR/trash/$SDAT/
rm -rf $EZCASTDIR/var/$ASSET
fi

if [ -e $STREAMING_INFO ]
then
    $PHP_PATH $CLI_STREAMING "close"
fi
