#!/bin/bash -x

# EZCAST EZrecorder
#
# Copyright (C) 2016 Université libre de Bruxelles
#
# Written by Michel Jansens <mjansens@ulb.ac.be>
# 	     Arnaud Wijns <awijns@ulb.ac.be>
# UI Design by Julien Di Pietrantonio
#
# This software is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#include localdefs
source $(dirname $0)/localdefs

ASSET=$1
CALLS=$2
MAXCALLS=3 	# sends a mail after 3 fails

#first clean up eventual movie remaining
SDAT=`date +"%Y_%m_%d_%Hh%M"`
mkdir  $RECORDDIR/trash/$SDAT 
mv $RECORDDIR/${COMMON_MOVIE_NAME}*.f4v  $RECORDDIR/trash/$SDAT/

osascript $EZCASTDIR/applescript/fmle_action.scpt&
wait

SDAT=`date +"%s"` 	#start date
WAITING_DELAY=4 	#if the file doesn't exist after 4s, we consider FMLE has planted
EXISTS_CAM=0 		# 1 if ${COMMON_MOVIE_NAME}.f4v exists on EZrecorder

# loop while delay hasn't expired and cam file doesn't exist
while [ $(( `date +"%s"`- $SDAT )) -le $WAITING_DELAY -a \( $EXISTS_CAM -eq 0 \) ]
do 
	# if cam didn't exist yet, checks if it exists now
	[ $EXISTS_CAM -eq 0 ] && test -e $RECORDDIR/${COMMON_MOVIE_NAME}.f4v && EXISTS_CAM=1;
	# if cam doesn't exist yet, wait 
	if [ $EXISTS_CAM -eq 0 ]
	then
		sleep 0.5
	fi
done


# add entry in log file 
[ $CALLS -eq 1 ] && echo "********************************************" >> $EZCASTDIR/var/_check_log
[ $CALLS -gt 1 ] && echo "--------------------------------------------" >> $EZCASTDIR/var/_check_log
echo `date +"%d/%m/%y - %Hh%Mm%Ss"` : Attempt $CALLS >> $EZCASTDIR/var/_check_log
echo "--------------------------------------------" >> $EZCASTDIR/var/_check_log
if [ $EXISTS_CAM -eq 1 ]; then echo "CAM (EZrecorder)   : Success" >> $EZCASTDIR/var/_check_log; else echo "CAM (EZrecorder)   : Failure" >> $EZCASTDIR/var/_check_log; fi;

# the file has not been found
if [ $EXISTS_CAM -eq 0 ]
then 
	if [ $CALLS -lt $MAXCALLS ]
	then
		# Quit FMLE
		osascript $EZCASTDIR/applescript/fmle_quit.scpt&
		wait
		# Kill FMLE if it hasn't been quit
		FMLE_CAM_PID=`ps ax | grep -i "FlashMediaLiveEncoder" | grep -v grep | cut -c 1-6`
		# Test if FMLE_CAM_PID is set
		if [ $FMLE_CAM_PID -gt 0 ]; then kill -9 $FMLE_CAM_PID; fi;

		$EZCASTDIR/bash/fmle_init $ASSET $(( $CALLS + 1 ))
	else
		echo "FAILURE FMLE"
		echo "FMLE Launch Failure in $CLASSROOM" | mail -s "FMLE Failure $CLASSROOM" $MAIL_TO
		echo -n "launch_failure" > $EZCASTDIR/var/status
	fi
else # currently recording
    #saves current date as recording init
    echo init:`date +%s`:`date +"%Y_%m_%d_%Hh%M"` > $EZCASTDIR/var/$ASSET/_cut_list

    #start monitoring 
    echo "$PHP_PATH $EZCASTDIR/cli_monitoring.php" | at now
fi