#!/bin/bash 

# EZCAST EZrecorder
#
# Copyright (C) 2014 Université libre de Bruxelles
#
# Written by Michel Jansens <mjansens@ulb.ac.be>
# 	     Arnaud Wijns <awijns@ulb.ac.be>
#            Antoine Dewilde
# UI Design by Julien Di Pietrantonio
#
# This software is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#include localdefs
source $(dirname $0)/localdefs

#filename and path of the result (cropped) image
LOCALSCREENSHOTPATH=$1

#take the snapshot and send it to the fifo
#screencapture -x -t tiff /tmp/screencapture.tiff
#warning CICrop rectangle=x_origin,y_origin,width,height 0,0 point is at bottom left!
#$EZCASTDIR/bin/CoreImageTool load myimage /tmp/screencapture.tiff filter myimage CICrop rectangle=350,650,290,205 store myimage $LOCALSCREENSHOTPATH public.jpeg&

seek_duration=`$FFPROBE_PATH -show_streams "$RECORDDIR/${COMMON_MOVIE_NAME}.f4v" 2> /dev/null | awk -F= '/^duration=/ { print $2-1 }' | awk 'NR>1{ print $1 }'` 
$FFMPEG_PATH -y -ss $seek_duration -i $RECORDDIR/${COMMON_MOVIE_NAME}.f4v -vframes 1 -s 427x240 $LOCALSCREENSHOTPATH 

echo $seek_duration >> /Library/ezrecorder/modules/cli_fmle/var/duration