#!/bin/bash -x

# EZCAST EZrecorder
#
# Copyright (C) 2014 Université libre de Bruxelles
#
# Written by Michel Jansens <mjansens@ulb.ac.be>
# 	     Arnaud Wijns <awijns@ulb.ac.be>
#            Antoine Dewilde
# UI Design by Julien Di Pietrantonio
#
# This software is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#include localdefs
source $(dirname $0)/localdefs

COURSE=$1
SDAT=$2
UPLOADDIR=$RECORDDIR/upload_to_server/${SDAT}_$COURSE
STORDIR=$RECORDDIR/upload_ok/${SDAT}_$COURSE

# transfers files from upload_to_server to upload_ok
echo "podcv: transfers files to upload_ok directory"
mv $UPLOADDIR $STORDIR

# removes all temp files used for the recording
mv $EZCASTDIR/var/${SDAT}_$COURSE/_cut_list $STORDIR
rm -rf $EZCASTDIR/var/${SDAT}_$COURSE