#!/bin/bash -x

# EZCAST EZrecorder
#
# Copyright (C) 2016 Université libre de Bruxelles
#
# Written by Michel Jansens <mjansens@ulb.ac.be>
# 	     Arnaud Wijns <awijns@ulb.ac.be>
#            Antoine Dewilde
# UI Design by Julien Di Pietrantonio
#
# This software is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#include localdefs
source $(dirname $0)/localdefs

ASSET=$1
REC_STATUS=`cat $STATUS`

#Verifies that the recording has been properly launched
if [ "$REC_STATUS" == "launch_failure" ]; then
    osascript $EZCASTDIR/applescript/fmle_open.scpt&
    osascript $EZCASTDIR/applescript/fmle_action.scpt&

    SDAT=`date +"%s"` 	#start date
    WAITING_DELAY=4 	#if the file doesn't exist after 4s, we consider FMLE has planted
    EXISTS_CAM=0 	# 1 if ${COMMON_MOVIE_NAME}.f4v exists on EZrecorder

    # loop while delay hasn't expired and cam file doesn't exist
    while [ $(( `date +"%s"`- $SDAT )) -le $WAITING_DELAY -a \( $EXISTS_CAM -eq 0 \) ]
    do 
	# if cam didn't exist yet, checks if it exists now
	[ $EXISTS_CAM -eq 0 ] && test -e $RECORDDIR/${COMMON_MOVIE_NAME}.f4v && EXISTS_CAM=1;
	# if cam doesn't exist yet, wait 
	if [ $EXISTS_CAM -eq 0 ]
	then
		sleep 0.5
	fi
    done

    if [ $EXISTS_CAM -eq 1 ]; then
        echo "open" >> $STATUS
    fi;
    echo init:`date +%s`:`date +"%Y_%m_%d_%Hh%M"` > $EZCASTDIR/var/$ASSET/_cut_list
fi;

echo play:`date +%s`:`date +"%Y_%m_%d_%Hh%M"` >> $EZCASTDIR/var/$ASSET/_cut_list
