#!/bin/bash
#include localdefs
source $(dirname $0)/localdefs

ACTION=$1
ASSET=$2

CUTLIST_FILE=$RECORDDIR/local_processing/$ASSET/remoteffmpeg/_cut_list.txt

DATE=`date +%s`
if [ "$ACTION" == "resume" ] 
then 
DATE=$[ $DATE + 5 ]
fi

echo $ACTION:$DATE:`date +"%Y_%m_%d_%Hh%M"` >> $CUTLIST_FILE
