#!/bin/bash -x

#include localdefs
source $(dirname $0)/localdefs

ASSET=$1

UPLOADDIR=$RECORDDIR/upload_to_server/$ASSET
STORDIR=$RECORDDIR/upload_ok/$ASSET

# transfers files from upload_to_server to upload_ok
echo "podcv: transfers files to upload_ok directory"
mv $UPLOADDIR $STORDIR

# removes all temp files used for the recording
rm -rf $STORDIR/*/low