#!/bin/bash -x

#process recording saved in a directory in ~/Movies/local_processing/${SDAT}_$COURSE 
#merge of movie parts + copy cam soundtrack to slide movie

#include localdefs
source $(dirname $0)/localdefs

ASSET=$1
PROCESSING_TOOL=$2

HANDLE_SOURCE_DIR=$EZCASTDIR/handle_source/$PROCESSING_TOOL
STORDIR=$RECORDDIR/local_processing/ffmpeg_$ASSET
TOSERVERDIR=$RECORDDIR/upload_to_server/$ASSET
CUTLIST_FILE=$EZCASTDIR/var/$ASSET/_cut_list

echo "command: ffmpeg_process_recording $ASSET"
#merge movies 
echo "local merge_movies.php<br>";
$PHP_PATH $HANDLE_SOURCE_DIR/merge_movies.php $STORDIR ${COMMON_MOVIE_NAME} slide.mov $CUTLIST_FILE

#now that processing has been done,
#move the directories in the upload_to_server section
if [ -d $TOSERVERDIR ]; then
    mv $STORDIR/* $TOSERVERDIR/.
    rm -rf $STORDIR
else 
    mv $STORDIR $TOSERVERDIR
fi
