#!/bin/bash -x

# EZCAST EZrecorder
#
# Copyright (C) 2014 Université libre de Bruxelles
#
# Written by Michel Jansens <mjansens@ulb.ac.be>
# 	     Arnaud Wijns <awijns@ulb.ac.be>
#            Antoine Dewilde
# UI Design by Julien Di Pietrantonio
#
# This software is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#include localdefs
source $(dirname $0)/localdefs

CALLS=$1
MAXCALLS=3 	# sends a mail after 3 fails

#first clean up eventual movie remaining
SDAT=`date +"%Y_%m_%d_%Hh%M"`
mkdir  $RECORDDIR/trash/$SDAT 
mv $RECORDDIR/${COMMON_MOVIE_NAME}*.mov  $RECORDDIR/trash/$SDAT/

osascript $EZCASTDIR/applescript/qtstartmovierec.scpt&
wait

SDAT=`date +"%s"` 	#start date
WAITING_DELAY=4 	#if the file doesn't exist after 4s, we consider QT has planted
EXISTS_CAM=0 		# 1 if ${COMMON_MOVIE_NAME}.mov exists on podcv

# loop while delay hasn't expired and cam file doesn't exist
while [ $(( `date +"%s"`- $SDAT )) -le $WAITING_DELAY -a \( $EXISTS_CAM -eq 0 \) ]
do 
	# if cam didn't exist yet, checks if it exists now
	[ $EXISTS_CAM -eq 0 ] && test -e $RECORDDIR/*\ Recording.mov && EXISTS_CAM=1;
	# if slide or cam doesn't exist yet, wait 
	if [ $EXISTS_CAM -eq 0 ]
	then
		sleep 0.5
	fi
done

#stop recording 
osascript $EZCASTDIR/applescript/qtstopmovierec.scpt $RECORDDIR/$COMMON_MOVIE_NAME.mov &
wait

# delete ${COMMON_MOVIE_NAME}.mov files 
rm $RECORDDIR/${COMMON_MOVIE_NAME}*.mov  
wait

# add entry in log file 
[ $CALLS -eq 1 ] && echo "********************************************" >> $EZCASTDIR/var/_dualqtcheck_log
[ $CALLS -gt 1 ] && echo "--------------------------------------------" >> $EZCASTDIR/var/_dualqtcheck_log
echo `date +"%d/%m/%y - %Hh%Mm%Ss"` : Attempt $CALLS >> $EZCASTDIR/var/_dualqbcheck_log
echo "--------------------------------------------" >> $EZCASTDIR/var/_dualqbcheck_log
if [ $EXISTS_CAM -eq 1 ]
then 
    echo "CAM (podcv)   : Success" >> $EZCASTDIR/var/_dualqtcheck_log
    if [ "$RECORD_TYPE" == "cam" ]
    then
        osascript $EZCASTDIR/applescript/qtnewmovie.scpt&
    else 
        osascript $EZCASTDIR/applescript/qtnewscreen.scpt&
    fi
else 
    echo "CAM (podcv)   : Failure" >> $EZCASTDIR/var/_dualqtcheck_log
fi;

# the file has not been found
if [ $EXISTS_CAM -eq 0 ]
then 
	if [ $CALLS -lt $MAXCALLS ]
	then
		# Quit QuickTime
		osascript $EZCASTDIR/applescript/qtquit.scpt&
		wait
		# Kill QuickTime if it hasn't been quit
		QT_CAM_PID=`ps ax | grep -i "QuickTime" | grep -v grep | cut -c 1-6`
		# Test if QT_CAM_PID is set
		if [ $QT_CAM_PID -gt 0 ]; then kill -9 $QT_CAM_PID; fi;

		$EZCASTDIR/bash/qtnew $(( $CALLS + 1 ))
	else
		echo "FAILURE QT"
		echo "QT Launch Failure in $CLASSROOM" | mail -s "QT Failure $CLASSROOM" $MAIL_TO
		echo -n "launch_failure" > $EZCASTDIR/var/status
	fi
fi