#!/bin/bash -x

# EZCAST EZrecorder
#
# Copyright (C) 2014 Université libre de Bruxelles
#
# Written by Michel Jansens <mjansens@ulb.ac.be>
# 	     Arnaud Wijns <awijns@ulb.ac.be>
#            Antoine Dewilde
# UI Design by Julien Di Pietrantonio
#
# This software is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#include localdefs
source $(dirname $0)/localdefs

if [ $# -eq 0 ]
then 
    CALLS=1
else 
    CALLS=$1
fi
#copy saved QTB prefs to the working prefs. This is done to avoid bad/destroyed prefs
#cp $EZCASTDIR/etc/com.apple.QuickTime\ Broadcaster.plist $USERQTBPREFS

if [ "$RECORD_TYPE" == "cam" ]
then
    osascript $EZCASTDIR/applescript/qtnewmovie.scpt&
else 
    osascript $EZCASTDIR/applescript/qtnewscreen.scpt&
fi
wait
#sleep 4
$EZCASTDIR/bash/resetpositions
#osascript $EZCASTDIR/applescript/positionqt.scpt
$EZCASTDIR/bash/qtcheck $CALLS 