#!/bin/bash -x
#global variables for scripts
EZCASTDIR=!PATH
RECORDDIR=!RECORD_PATH
STARTRECTIMEPATH=/tmp/qtb_start_rec_time
USERQTBPREFS=~/Library/Preferences/com.apple.QuickTime\ Broadcaster.plist
COMMON_MOVIE_NAME=qtbmovie
MAIL_TO=!MAIL_TO
CLASSROOM=!CLASSROOM
PHP_PATH=!PHP_PATH