#!/bin/bash -x

# EZCAST EZrecorder
#
# Copyright (C) 2016 Université libre de Bruxelles
#
# Written by Michel Jansens <mjansens@ulb.ac.be>
# 	     Arnaud Wijns <awijns@ulb.ac.be>
#            Antoine Dewilde
# UI Design by Julien Di Pietrantonio
#
# This software is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#include localdefs
source $(dirname $0)/localdefs

#process recording saved in a directory in /Users/podclient/Movies/local_processing/${SDAT}_$COURSE 
#merge of movie parts + copy cam soundtrack to slide movie

COURSE=$1
SDAT=$2
PROCESSING_TOOL=$3
HANDLE_DUALSOURCE_DIR=$EZCASTDIR/handle_source/$PROCESSING_TOOL
STORDIR=$RECORDDIR/local_processing/${SDAT}_$COURSE
TOSERVERDIR=$RECORDDIR/upload_to_server/${SDAT}_$COURSE

mv $EZCASTDIR/var/_first_started $STORDIR
mv $EZCASTDIR/var/_last_request $STORDIR
mv $EZCASTDIR/var/status $STORDIR
mv $EZCASTDIR/var/_metadata.xml $STORDIR

echo "command: dualqtb_process_recording $COURSE $SDAT"
#merge movies and copy soundtrack
echo "local merge_qtb_movies.php<br>";
$PHP_PATH $HANDLE_DUALSOURCE_DIR/merge_qtb_movies.php $STORDIR $COMMON_MOVIE_NAME slide.mov

#now that processing has been done,
#move the directories in the upload_to_server section
mv $STORDIR $TOSERVERDIR

