#!/bin/bash -x

# EZCAST EZrecorder
#
# Copyright (C) 2016 Université libre de Bruxelles
#
# Written by Michel Jansens <mjansens@ulb.ac.be>
# 	     Arnaud Wijns <awijns@ulb.ac.be>
#            Antoine Dewilde
# UI Design by Julien Di Pietrantonio
#
# This software is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#include localdefs
source $(dirname $0)/localdefs
#SDAT=`cat ${STARTRECTIMEPATH}`
COURSE=$1
SDAT=$2
PROCESSING_TOOL=$3
STORDIR=$RECORDDIR/local_processing/${SDAT}_$COURSE
METADATAPATH=$EZCASTDIR/var/_metadata.xml

osascript $EZCASTDIR/applescript/qtbstopmovierec.scpt&
#wait for both stop to finish
wait

#save ${COMMON_MOVIE_NAME}*.mov on slide and cam beware that files are saved as 2GB max chuncks

#stop monitoring
unlink $EZCASTDIR/var/_monitoring_pid

echo "podcv:saving slide movie to $STORDIR<br>"
mkdir $STORDIR
mv $RECORDDIR/${COMMON_MOVIE_NAME}*.mov $STORDIR 
#copy metadatas
mv $METADATAPATH  $STORDIR/metadata.xml 

#close screen sharing window
#osascript $EZCASTDIR/applescript/closescreensharing.scpt

#echo "/usr/bin/nice -n 10 $EZCASTDIR/bash/qtb_process_recording $COURSE $SDAT >$STORDIR/processing.log 2>&1"|at now 
/usr/bin/nice -n 10 $EZCASTDIR/bash/qtb_process_recording $COURSE $SDAT $PROCESSING_TOOL >$STORDIR/processing.log 2>&1
